spring:
  application:
    name: grocery-scout-backend
  profiles:
    active: dev
  
  # Persistence Layer
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # JSON Serialization
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null

  # Conditional Autoconfiguration
  # Autoconfiguration
  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Session Management
server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: lax
        max-age: 3600
      timeout: 1h

# Global Configuration
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Feature Toggles
kafka:
  enabled: true
